apiVersion: v1
kind: Service
metadata:
  name: spring-rest-api
  labels:
    app: spring-rest-api
  # namespace: nginx
spec:
  type: NodePort
  ports:
  - port: 8080 # service-port: port exposed internally in the cluster
#    nodePort: 30163 # a static port assigned on each the node
    targetPort: 8080 # the container port to send requests to
  selector: # Specify which pods will be exposed by this service
            # Should be match with the label for pod 
    app: spring-rest-api
    

#kubectl port-forward svc/nginx-svc 8082:81 (hostPort:servicePort)
#http://nodeIP:nodePort